version: '3.7'
services:
  http-transcoder:
    image: envoyproxy/envoy
    volumes:
      - ./envoy.config.yml:/etc/envoy/envoy.yaml:ro
      - ./target/greeter.pb:/data/greeterService.pb
    ports:
      - 51051:51051
      - 9901:9901
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/server
    environment:
      - RUST_LOG=rist-grpc
      - RUST_BACKTRACE=all
    ports:
      - 50051:50051

  ambassador:
    image: quay.io/datawire/ambassador:0.85.0
    ports:
    - 8080:8080
    volumes:
    # mount a volume where we can inject configuration files
    - ./ambassador:/ambassador/ambassador-config
    environment:
    # don't try to watch Kubernetes for configuration changes
    - AMBASSADOR_NO_KUBEWATCH=no_kubewatch
  tour-ui:
    image: quay.io/datawire/tour:ui-0.2.6
    ports:
    - 5000
  tour-backend:
    image: quay.io/datawire/tour:backend-0.2.6
    ports:
    - 8080
  auth:
    image: datawire/ambassador-auth-service:latest
    ports:
    - 3000
  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports: 
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411